### ISSUE TITLE
Seems not working on mobile browsers

### ISSUE THREAD

**Issue by rubenaprikyan** [jkgenser/react-pdf-headless#15]
Tried to use on mobile browsers but it doesn't work.

It always renders loading component. No errors.

**Comment by jkgenser** [comment]
Interesting. I haven't deployed this on mobile at all but I'll test it out. Any particular OS and browser combination so that I can try reproducing what you're experiencing?

**Comment by rubenaprikyan** [comment]
I think thats all the same, used different versions. Both on Android and IOS. Safari, Chrome.

fyi also tried your demo project for that, just broadcasting with `vite --host`.

**Comment by rubenaprikyan** [comment]
@jkgenser  Have you had a chance to look at this?

**Comment by jkgenser** [comment]
> @jkgenser Have you had a chance to look at this?

No, not yet.

**Comment by jkgenser** [comment]
> @jkgenser Have you had a chance to look at this?

I just tried logging in to my application that uses this library on mobile. Using android and chrome and the PDF viewer was able to load.

**Comment by rubenaprikyan** [comment]
> > @jkgenser Have you had a chance to look at this?
> 
> I just tried logging in to my application that uses this library on mobile. Using android and chrome and the PDF viewer was able to load.

That's great it is working, then the problem is related to bundling I guess.
I use Next 14 and deployed on Vercel. But it doesn't work on local environment as well.

Does your app using Nextjs ?

**Comment by jkgenser** [comment]
> > > @jkgenser Have you had a chance to look at this?
> > 
> > 
> > I just tried logging in to my application that uses this library on mobile. Using android and chrome and the PDF viewer was able to load.
> 
> That's great it is working, then the problem is related to bundling I guess. I use Next 14 and deployed on Vercel. But it doesn't work on local environment as well.
> 
> Does your app using Nextjs ?

I am using Vite in my build. Do you have any details on what exactly isn't working, e.g. from console?

In your build, have you tested that it works on web and it's only mobile that doesn't work?

**Comment by rubenaprikyan** [comment]
> I have some logic that manually fetches the worker code
> 
> ```ts
> import * as pdfjs from 'pdfjs-dist';
> 
> export async function fetchWithRetry(
>   url: string,
>   retries: number = 2,
> ): Promise<void> {
>   const attemptFetch = async (attempt: number): Promise<void> => {
>     try {
>       const response = await fetch(url);
>       if (!response.ok) {
>         throw new Error(`HTTP error! status: ${response.status}`);
>       }
>       const workerScript = await response.text();
>       const blob = new Blob([workerScript], { type: 'application/javascript' });
>       const workerUrlBlob = URL.createObjectURL(blob);
>       pdfjs.GlobalWorkerOptions.workerPort = new Worker(workerUrlBlob);
>       pdfjs.GlobalWorkerOptions.workerSrc = workerUrlBlob;
>     } catch (error) {
>       if (attempt < retries) {
>         console.log(`Retrying fetch... Attempt ${attempt + 1}`);
>         await attemptFetch(attempt + 1);
>       } else {
>         console.error('Error loading PDF worker script', error);
>         pdfjs.GlobalWorkerOptions.workerSrc = url;
>       }
>     }
>   };
> 
>   await attemptFetch(0);
> }
> ```
> 
> ```ts
> import { useEffect } from 'react';
> import { create } from 'zustand';
> import { fetchWithRetry } from '../api/pdf';
> 
> interface FetchState {
>   isPdfWorkerFetched: boolean;
>   setIsFetched: () => void;
> }
> 
> export const usePdfFetchedStore = create<FetchState>((set) => ({
>   isPdfWorkerFetched: false,
>   setIsFetched: () => set({ isPdfWorkerFetched: true }),
> }));
> 
> const usePdfWorker = ({ pdfWorkerUrl }: { pdfWorkerUrl: string }) => {
>   const { setIsFetched } = usePdfFetchedStore();
>   useEffect(() => {
>     const loadPdfWorker = async () => {
>       try {
>         await fetchWithRetry(pdfWorkerUrl, 3);
>         setIsFetched();
>       } catch (error) {
>         console.error('Failed to load PDF worker script:', error);
>       }
>     };
> 
>     loadPdfWorker();
>   }, []);
> };
> 
> export default usePdfWorker;
> ```
> 
> I've seen a lot of different ways for apps to fetch the worker. That's one of the most common ways that using pdf.js can get tripped up. You can read more about other ways to try a worker fetch setup that works for you here: https://github.com/wojtekmaj/react-pdf (this library depends on)

I wrote a script to copy build file into `/public` folder during CI, in this way it works on web browsers 

```js
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
```
There is another issue saying Promise.withResolvers is not defined, which is probably related to the nodejs version used next. Let me try the worker loading code you have shared and share the result

**Comment by rubenaprikyan** [comment]
@jkgenser

Solved this issue by injecting this polyfill and using legacy build of `pdfjs-dist`

```ts
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;

```

```ts
export function promisePolyfill() {
  if (typeof Promise.withResolvers === 'undefined') {
    if (typeof window !== 'undefined') {
      // @ts-ignore
      Promise.withResolvers = function () {
        let resolveFunc: (value: any) => void;
        let rejectFunc: (reason?: any) => void;

        const promise = new Promise((resolve, reject) => {
          resolveFunc = resolve;
          rejectFunc = reject;
        });

        return {
          promise,
          resolve: resolveFunc!,
          reject: rejectFunc!,
        };
      };
    }
  }
}

```

**Comment by rubenaprikyan** [comment]
@jkgenser 
Closing this issue since its not related to the library
